Repository aisvn-data/solarpower, pull requests merged in 2020-12, with the labels that each got.

#6 restructured, new measureVoltages() function
  software/SolarAISVN/SolarAISVN.ino
Labels: enhancement

#3 submit corrected data
  docs/2020-06-11_datacollection.png
  docs/2020-06-12_roof.jpg
  docs/2020-06-12_setup.jpg
  docs/20200605_circuit.png
  docs/TTGO_ESP32.jpg
  docs/adc_esp32.jpg
  docs/analog_input_esp32.jpg
  docs/index.md
  docs/setup_2020-03-20.jpg
  software/SolarAISVN/SolarAISVN.ino
Labels: documentation, enhancement, help wanted

#4 pin34 raw transmission
  software/SolarAISVN/SolarAISVN.ino
Labels: documentation

#8 Update SolarAISVN.ino
  software/SolarAISVN/SolarAISVN.ino
Labels: documentation
